import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/user_model.dart';
import '../models/meal_model.dart';


class ExportService {
  static const _blue900 = PdfColors.blue900;
  static const _grey700 = PdfColors.grey700;
  static const _grey300 = PdfColors.grey300;

  static Future<void> exportToPdf(
    UserModel user,
    List<MealModel> meals, {
    double? calorieTarget,
    double? proteinTarget,
    double? carbsTarget,
    double? fatTarget,
  }) async {
    final pdf = pw.Document();

    final now = DateTime.now();
    final String displayDate = '${now.day}/${now.month}/${now.year}';

    // ---- Aggregate nutrition ----
    final totalCalories = meals.fold<int>(0, (sum, m) => sum + m.calories);
    final totalProtein = meals.fold<double>(0, (sum, m) => sum + m.protein);
    final totalCarbs = meals.fold<double>(0, (sum, m) => sum + m.carbs);
    final totalFat = meals.fold<double>(0, (sum, m) => sum + m.fat);

    // ---- BMI ----
    final heightM = user.heightCm / 100;
    final bmi = heightM > 0 ? user.weightKg / (heightM * heightM) : 0.0;
    final bmiCategory = _bmiCategory(bmi);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(32, 32, 32, 40),
        header: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Nutrition & Glucose Report',
                  style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: _blue900),
                ),
                pw.Text(displayDate, style: pw.TextStyle(fontSize: 11, color: _grey700)),
              ],
            ),
            pw.SizedBox(height: 4),
            pw.Text(
              'Generated by Smart Diet Assistant — for clinical review',
              style: pw.TextStyle(fontSize: 9, color: _grey700, fontStyle: pw.FontStyle.italic),
            ),
            pw.SizedBox(height: 12),
            pw.Divider(thickness: 1, color: _grey300),
          ],
        ),
        footer: (context) => pw.Column(
          children: [
            pw.Divider(thickness: 0.5, color: _grey300),
            pw.SizedBox(height: 4),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Self-reported data. Corroborate with clinical assessment before treatment decisions.',
                  style: pw.TextStyle(fontSize: 8, color: _grey700),
                ),
                pw.Text(
                  'Page ${context.pageNumber} of ${context.pagesCount}',
                  style: pw.TextStyle(fontSize: 8, color: _grey700),
                ),
              ],
            ),
          ],
        ),
        build: (context) => [
          // ---- Patient Summary ----
          _sectionHeader('Patient Summary'),
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
            ),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      _infoRow('Gender', user.gender),
                      _infoRow('Age', '${user.age} years'),
                      _infoRow('Weight', '${user.weightKg} kg'),
                      _infoRow('Height', '${user.heightCm.round()} cm'),
                    ],
                  ),
                ),
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      _infoRow('BMI', '${bmi.toStringAsFixed(1)} ($bmiCategory)'),
                      pw.SizedBox(height: 4),
                      pw.Text('Medical Conditions', style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: _grey700)),
                      pw.SizedBox(height: 2),
                      pw.Text(
                        user.conditions.isEmpty ? 'None reported' : user.conditions.join(', '),
                        style: const pw.TextStyle(fontSize: 10),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),

          pw.SizedBox(height: 20),

          // ---- Nutrition Summary ----
          _sectionHeader('Nutrition Summary'),
          pw.Table.fromTextArray(
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white, fontSize: 10),
            headerDecoration: const pw.BoxDecoration(color: _blue900),
            cellStyle: const pw.TextStyle(fontSize: 10),
            cellAlignment: pw.Alignment.centerLeft,
            cellPadding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
            border: pw.TableBorder.all(color: _grey300, width: 0.5),
            headers: ['Metric', 'Intake', 'Target', '% of Target'],
            data: [
              _nutritionRow('Calories', totalCalories.toDouble(), calorieTarget, 'kcal'),
              _nutritionRow('Protein', totalProtein, proteinTarget, 'g'),
              _nutritionRow('Carbohydrates', totalCarbs, carbsTarget, 'g'),
              _nutritionRow('Fat', totalFat, fatTarget, 'g'),
            ],
          ),

          pw.SizedBox(height: 20),



          // ---- Meal Breakdown ----
          _sectionHeader('Meal Breakdown'),
          pw.Table.fromTextArray(
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white, fontSize: 10),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey700),
            cellStyle: const pw.TextStyle(fontSize: 10),
            cellPadding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
            border: pw.TableBorder.all(color: _grey300, width: 0.5),
            headers: ['Meal', 'Item', 'Calories', 'Protein (g)', 'Carbs (g)', 'Fat (g)'],
            data: meals
                .map((m) => [
                      m.type.name[0].toUpperCase() + m.type.name.substring(1),
                      m.name,
                      '${m.calories}',
                      m.protein.toStringAsFixed(0),
                      m.carbs.toStringAsFixed(0),
                      m.fat.toStringAsFixed(0),
                    ])
                .toList(),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }

  static pw.Widget _sectionHeader(String title) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 8),
        child: pw.Text(title, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 14, color: _blue900)),
      );

  static pw.Widget _infoRow(String label, String value) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 3),
        child: pw.RichText(
          text: pw.TextSpan(
            children: [
              pw.TextSpan(text: '$label: ', style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: _grey700)),
              pw.TextSpan(text: value, style: const pw.TextStyle(fontSize: 10)),
            ],
          ),
        ),
      );

  static List<dynamic> _nutritionRow(String label, double intake, double? target, String unit) {
    if (target == null || target <= 0) {
      return [label, '${intake.toStringAsFixed(0)} $unit', '-', '-'];
    }
    final pct = (intake / target * 100).toStringAsFixed(0);
    return [label, '${intake.toStringAsFixed(0)} $unit', '${target.toStringAsFixed(0)} $unit', '$pct%'];
  }

  static String _bmiCategory(double bmi) {
    if (bmi <= 0) return 'N/A';
    if (bmi < 18.5) return 'Underweight';
    if (bmi < 25) return 'Normal';
    if (bmi < 30) return 'Overweight';
    return 'Obese';
  }
}