import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter_animate/flutter_animate.dart';
import '../providers/user_provider.dart';
import '../models/shopping_item.dart';

class ShoppingListScreen extends StatefulWidget {
  const ShoppingListScreen({super.key});

  @override
  State<ShoppingListScreen> createState() => _ShoppingListScreenState();
}

class _ShoppingListScreenState extends State<ShoppingListScreen> {
  List<String> _weeklyList = [];
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    _loadWeeklyList();
  }

  Future<void> _loadWeeklyList() async {
    setState(() => _isLoading = true);
    final provider = Provider.of<UserProvider>(context, listen: false);
    _weeklyList = await provider.getWeeklyShoppingList();
    if (mounted) setState(() => _isLoading = false);
  }

  @override
  Widget build(BuildContext context) {
    final provider = Provider.of<UserProvider>(context);
    final autoGeneratedItems = _weeklyList;
    final customItems = provider.customShoppingItems;
    final checkedItems = provider.checkedIngredients;

    // Combine into unified list
    List<ShoppingItem> combinedList = [];
    
    for (var item in autoGeneratedItems) {
      combinedList.add(ShoppingItem(id: item, name: item, isCustom: false));
    }
    combinedList.addAll(customItems);

    // Sort by target date (urgent first)
    combinedList.sort((a, b) {
      if (a.targetDate != null && b.targetDate != null) {
        return a.targetDate!.compareTo(b.targetDate!);
      } else if (a.targetDate != null) {
        return -1; // a comes first
      } else if (b.targetDate != null) {
        return 1; // b comes first
      }
      return 0; // both null, preserve order (or we could sort alphabetically)
    });

    // Filter list into to-buy and completed
    final toBuy = combinedList.where((item) => !checkedItems.contains(item.id)).toList();
    final completed = combinedList.where((item) => checkedItems.contains(item.id)).toList();

    return Scaffold(
      backgroundColor: Theme.of(context).scaffoldBackgroundColor,
      appBar: AppBar(
        title: Text(
          'Shopping List',
          style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: Theme.of(context).colorScheme.onSurface),
        ),
        backgroundColor: Theme.of(context).scaffoldBackgroundColor,
        elevation: 0,
        actions: [
          if (checkedItems.isNotEmpty)
            TextButton(
              onPressed: () => provider.clearCheckedIngredients(),
              child: Text(
                'Clear All',
                style: GoogleFonts.outfit(color: Colors.red, fontWeight: FontWeight.w600),
              ),
            ),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: _isLoading
                ? const Center(child: CircularProgressIndicator())
                : combinedList.isEmpty
                    ? _buildEmptyState()
                    : ListView(
                        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
                        children: [
                          if (toBuy.isNotEmpty) ...[
                            _buildSectionHeader(context, 'To Buy', toBuy.length),
                            ...toBuy.map((item) => _buildShoppingItem(context, provider, item, false)),
                          ],
                          if (completed.isNotEmpty) ...[
                            const SizedBox(height: 24),
                            _buildSectionHeader(context, 'Completed', completed.length),
                            ...completed.map((item) => _buildShoppingItem(context, provider, item, true)),
                          ],
                          const SizedBox(height: 80), // Padding for FAB
                        ],
                      ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () => _showAddItemDialog(context, provider),
        backgroundColor: Theme.of(context).colorScheme.primary,
        icon: Icon(Icons.add, color: Theme.of(context).colorScheme.onPrimary),
        label: Text(
          'Add Item',
          style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: Theme.of(context).colorScheme.onPrimary),
        ),
      ),
    );
  }

  void _showAddItemDialog(BuildContext context, UserProvider provider) {
    final nameController = TextEditingController();
    DateTime? selectedDate;

    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Theme.of(context).scaffoldBackgroundColor,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      builder: (context) {
        return StatefulBuilder(
          builder: (context, setModalState) {
            return Padding(
              padding: EdgeInsets.only(
                bottom: MediaQuery.of(context).viewInsets.bottom,
                left: 24,
                right: 24,
                top: 24,
              ),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Add Custom Item',
                    style: GoogleFonts.outfit(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                      color: Theme.of(context).colorScheme.onSurface,
                    ),
                  ),
                  const SizedBox(height: 16),
                  TextField(
                    controller: nameController,
                    decoration: InputDecoration(
                      labelText: 'Item Name',
                      border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                    ),
                  ),
                  const SizedBox(height: 16),
                  ListTile(
                    contentPadding: EdgeInsets.zero,
                    title: Text(
                      selectedDate == null 
                          ? 'Select Target Date (Optional)' 
                          : 'Target Date: ${selectedDate!.toString().substring(0, 10)}',
                      style: GoogleFonts.outfit(
                        color: selectedDate == null ? Colors.grey : Theme.of(context).colorScheme.onSurface,
                      ),
                    ),
                    trailing: Icon(Icons.calendar_today, color: Theme.of(context).colorScheme.primary),
                    onTap: () async {
                      final date = await showDatePicker(
                        context: context,
                        initialDate: DateTime.now(),
                        firstDate: DateTime.now().subtract(const Duration(days: 1)),
                        lastDate: DateTime.now().add(const Duration(days: 365)),
                      );
                      if (date != null) {
                        setModalState(() => selectedDate = date);
                      }
                    },
                  ),
                  const SizedBox(height: 24),
                  SizedBox(
                    width: double.infinity,
                    child: ElevatedButton(
                      onPressed: () {
                        if (nameController.text.trim().isNotEmpty) {
                          provider.addCustomShoppingItem(ShoppingItem(
                            id: DateTime.now().millisecondsSinceEpoch.toString(),
                            name: nameController.text.trim(),
                            targetDate: selectedDate,
                            isCustom: true,
                          ));
                          Navigator.pop(context);
                        }
                      },
                      style: ElevatedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                        backgroundColor: Theme.of(context).colorScheme.primary,
                        foregroundColor: Theme.of(context).colorScheme.onPrimary,
                      ),
                      child: Text('Add Item', style: GoogleFonts.outfit(fontWeight: FontWeight.bold)),
                    ),
                  ),
                  const SizedBox(height: 24),
                ],
              ),
            );
          },
        );
      },
    );
  }

  Widget _buildSectionHeader(BuildContext context, String title, int count) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12, top: 8),
      child: Row(
        children: [
          Text(
            title,
            style: GoogleFonts.outfit(
              fontSize: 18,
              fontWeight: FontWeight.bold,
              color: Theme.of(context).colorScheme.onSurface,
            ),
          ),
          const SizedBox(width: 8),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
            decoration: BoxDecoration(
              color: Colors.grey.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Text(
              '$count',
              style: GoogleFonts.outfit(fontSize: 12, color: Theme.of(context).colorScheme.onSurfaceVariant),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildShoppingItem(BuildContext context, UserProvider provider, ShoppingItem item, bool isChecked) {
    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      padding: const EdgeInsets.all(4),
      decoration: BoxDecoration(
        color: Theme.of(context).cardTheme.color ?? Theme.of(context).colorScheme.surface,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.02),
            blurRadius: 5,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: CheckboxListTile(
        value: isChecked,
        onChanged: (_) => provider.toggleIngredient(item.id),
        controlAffinity: ListTileControlAffinity.leading,
        activeColor: Theme.of(context).colorScheme.primary,
        checkboxShape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6)),
        title: Text(
          item.name,
          style: GoogleFonts.outfit(
            fontSize: 16,
            color: isChecked ? Colors.grey : Theme.of(context).colorScheme.onSurface,
            decoration: isChecked ? TextDecoration.lineThrough : null,
          ),
        ),
        subtitle: item.targetDate != null
            ? Text(
                'Needed by: ${item.targetDate!.toString().substring(0, 10)}',
                style: GoogleFonts.outfit(
                  fontSize: 12,
                  color: isChecked ? Colors.grey : Theme.of(context).colorScheme.primary,
                ),
              )
            : null,
        secondary: item.isCustom
            ? IconButton(
                icon: const Icon(Icons.delete_outline, color: Colors.redAccent),
                onPressed: () => provider.removeCustomShoppingItem(item.id),
              )
            : null,
      ),
    ).animate().fadeIn().slideX(begin: 0.05);
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.shopping_basket_outlined, size: 80, color: Colors.grey.withValues(alpha: 0.3)),
          const SizedBox(height: 16),
          Text(
            'Your shopping list is empty',
            style: GoogleFonts.outfit(fontSize: 18, color: Colors.grey, fontWeight: FontWeight.w500),
          ),
          const SizedBox(height: 8),
          Text(
            'Add custom items or meals to your plan!',
            style: GoogleFonts.outfit(fontSize: 14, color: Colors.grey.withValues(alpha: 0.7)),
          ),
        ],
      ),
    );
  }
}

